### ISSUE TITLE
Issue still persists on ubuntu environment with alpine

### ISSUE THREAD

**Issue by anantjain06** [ultimateakash/puppeteer-html-pdf#14]
Issue still persists

I have used same dependencies in my docker file on ubuntu environment

Alpine image version :   FROM node:14.17.6-alpine

# Install necessary dependencies
 for Puppeteer
RUN apk add --no-cache \
    chromium \
    nss \
    freetype \
    freetype-dev \
    harfbuzz \
    ca-certificates \
    ttf-freefont
    
    In NODE JS i am using below code
    
    const htmlPDF = new PuppeteerHTMLPDF();
            const htmloptions = {
                executablePath: '/usr/bin/chromium-browser',
                format: "A4",
                path: config.filepath + newFilename, // you can pass path to save the file
                headless: false
              };
              htmlPDF.setOptions(htmloptions);
              const htmlPdfContent = html;
                try {
                    console.log("PDF PRINTED")
                    //await htmlPDF.create(htmlPdfContent);
                    htmlPDF.create(htmlPdfContent, (err, result) => {
                        if (err) {
                            logger.log(err, constants.logLevels.ERROR);
                            deferred.reject(err);
                        } else {
                            console.log(result)
                            deferred.resolve({ filePath: config.apiUrl + '/' + newFilename, fileName: newFilename });
                        }
                    });
                   
                } catch (error) {
                    console.log("PuppeteerHTMLPDF error", error);
             }
    
    
    It is showing nothing on server console and not printing any PDF and loader is continuously spinning
    
    **Here is error showing on server console** 
    
    **(node:24) UnhandledPromiseRejectionWarning: Error: Failed to connect to browser: Failed to launch the browser process! undefined
[47:47:0509/134018.681473:ERROR:browser_main_loop.cc(1485)] Unable to open X display.
 
 
TROUBLESHOOTING: https://pptr.dev/troubleshooting
 
    at PuppeteerHTMLPDF.initializeBrowser (/app/node_modules/puppeteer-html-pdf/lib/index.js:143:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async PuppeteerHTMLPDF.create (/app/node_modules/puppeteer-html-pdf/lib/index.js:31:5)
(node:24) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)**
    
    
Note : same code is working fine on my windows machine.

**Comment by ultimateakash** [comment]
@anantjain06, it appears that you're trying to use Puppeteer with **headless: false** mode. This configuration requires access to an X display, which is not available in your current setup, leading to the error "Unable to open X display."

To resolve this issue, you have two options:

1. **Use headless mode (headless: true):** Puppeteer is designed to work seamlessly in headless mode, which doesn't require access to a graphical environment. Changing your Puppeteer configuration to headless: true should resolve the error without requiring any additional dependencies.

2. **Install graphical interface dependencies:** If you must use Puppeteer with headless: false, you'll need to install additional dependencies to provide support for the graphical environment. You can add dependencies like Xvfb and configure Puppeteer to use it. However, this approach adds complexity to your setup and may not be necessary if your application doesn't require a visible browser window.

**Comment by anantjain06** [comment]
After applying headless: true it is still not working and it is not showing any error as well.

**Comment by ultimateakash** [comment]
@anantjain06  please share your Dockerfile and also tell me your node version and puppeteer-html-pdf version.

**Comment by anantjain06** [comment]
"puppeteer-html-pdf": "^3.0.4"


Here is docker file :

FROM node:14.17.6-alpine
 
WORKDIR /app
 
COPY . /app
 
RUN ls -la
 
RUN cat config/config.js
 
#Add rendering essentials
RUN apk add --no-cache fontconfig ttf-dejavu
 
RUN apk --update add redis git
 
# Install necessary dependencies for Puppeteer
RUN apk add --no-cache \
    chromium \
    nss \
    freetype \
    freetype-dev \
    harfbuzz \
    ca-certificates \
    ttf-freefont
 
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

RUN npm install multiparty
 
RUN npm install --force

RUN npm install aws-sdk
 
RUN npm install -g npm@9.6.4
 
CMD npm run staging

**Comment by ultimateakash** [comment]
Hello @anantjain06,

I've replicated the issue you're facing and discovered that it seems to be specific to the `node:14.17.6-alpine` image. To resolve this, I suggest changing the Alpine image version.

I conducted tests with three different images:

1. `FROM node:14.19.2-alpine`
2. `FROM node:14-alpine`
3. `FROM node:alpine`

All three worked without any issues.

This problem has also been reported on the official Puppeteer repository. You can find more details in the following reference: [Puppeteer Issue #1793](https://github.com/puppeteer/puppeteer/issues/1793).

**Comment by anantjain06** [comment]
Hello @ultimateakash 

Issue has been resolved related to PDF generation but generated PDF is having issue in table format as i have attached in same thread

so how i can resolve means what width or height aspect ratio i need to provide as columns would be properly
 visible.
 
 ![CSS-ISSUE](https://github.com/ultimateakash/puppeteer-html-pdf/assets/22386954/09c25457-29a2-47f9-8b2b-e926fe8e8c7f)

**Comment by ultimateakash** [comment]
@anantjain06, adjust the width properties of the `table`, `th (table header)`, and `td (table data)` elements as needed to ensure your table content fits well within the `A4` page dimensions. This is a CSS adjustment and doesn't directly relate to puppeteer-html-pdf. If you encounter any other issues, feel free to reopen or raise them.
